# --- Import ---
import streamlit as st
from analyzer import analyze_text
import pandas as pd 
import plotly.graph_objects as go 

# --- Charts Visualization ---
def create_donut_chart(data_dict, title):
    if not data_dict or sum(data_dict.values()) == 0:
        st.write(f"No data to visualize for {title}.")
        return None

    labels = list(data_dict.keys())
    values = list(data_dict.values())
    
    fig = go.Figure(data=[go.Pie(
        labels=labels, 
        values=values, 
        hole=.4,
        marker=dict(line=dict(color='#FFFFFF', width=2)),
        pull=[0.02] * len(labels),
        textinfo='percent',
        hoverinfo='label+value'
    )])
    
    fig.update_layout(
        title=dict(text=title, x=0.5, xanchor='center'),
        showlegend=True,
        legend=dict(orientation="h", yanchor="bottom", y=-0.3, xanchor="center", x=0.5, font=dict(size=10)),
        margin=dict(t=40, b=0, l=0, r=0),
        height=280 
    )
    
    return fig

# --- Display Detect Sentiment Context ---
def render_sentiment_context(sentiment_data, positive_label="Positive", negative_label="Negative", neutral_label="Neutral"):
    st.markdown(f"**Sentiment Context:**")
    st.write(f"{positive_label}: **{sentiment_data.get('positive', 0)}**")
    st.write(f"{negative_label}: **{sentiment_data.get('negative', 0)}**")
    if 'neutral' in sentiment_data and sentiment_data.get('neutral', 0) > 0:
        st.write(f"{neutral_label}: **{sentiment_data['neutral']}**")


# --- Page Configuration ---
st.set_page_config(
    page_title="Bias Detection Dashboard",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# --- Header ---
st.title("🤖 Bias Detection Dashboard for LLM Outputs")
st.markdown("""
This tool helps you analyze text generated by AI models to identify potential social biases 
related to gender, religion, nationality/ethnicity, and occupation.
""")
st.markdown("---")

# --- Language List ---
selected_language = st.selectbox(
    'Select Language for Analysis',
    ('English', 'Arabic')
)

# --- Text Input Box ---
st.subheader("Enter the text you want to analyze")
user_input = st.text_area(
    label="Paste your text here", 
    height=250, 
    label_visibility="collapsed",
    placeholder="Paste your text here..."
)

# --- Button ---
analyze_button = st.button("Analyze Text", type="primary")

if analyze_button:
    if user_input:
        # --- Arabic Coverage Notes ---
        if selected_language == 'Arabic':
            st.markdown("---")
            st.info("""
            **ملاحظة حول دعم اللغة العربية:**

            اللغة العربية لغة عظيمة وغنية بالإضافات والتراكيب المعقدة. النموذج الحالي للتحليل لا يزال بسيطاً وقيد التطوير، لذلك قد تكون النتائج المعروضة للغة العربية غير مكتملة لأن القواميس المستخدمة وأدوات التحليل ليست شاملة بعد.
            """)
        
        with st.spinner('Analyzing text... (Loading new models might take time on first run)'):
            results = analyze_text(user_input, language=selected_language) #Sending Input To analyzer.py
        
        st.markdown("---")
        st.subheader("📊 Analysis Summary")

        # --- Summary Coloums ---
        col1, col2, col3, col4 = st.columns(4)
        
        with col1:
            gender_total = results['gender_analysis']['male_count'] + results['gender_analysis']['female_count']
            st.metric(label="Gendered Words Found", value=gender_total)
        with col2:
            st.metric(label="Religious Terms Found", value=results['religion_analysis']['count'])
        with col3:
            st.metric(label="Nationality Terms Found", value=results['nationality_ethnicity_analysis']['count'])
        with col4:
            job_total = results['occupation_analysis']['male_job_count'] + results['occupation_analysis']['female_job_count']
            st.metric(label="Occupational Terms Found", value=job_total)

        # --- Imbalance Score ---
        st.subheader("📈 Overall Gender/Occupation Imbalance Score")
        st.markdown("_(0% = Perfectly Balanced, 100% = Completely Skewed to one side)_")
        st.markdown("_(Scores are based on word counts only)_")
        combined_score = results['overall_scores']['combined_bias_score']
        st.write(f"**Overall Imbalance Score: {combined_score}%**")
        st.progress(combined_score / 100) 
        
        st.markdown("---") 

        st.subheader("🔍 Detailed Breakdown")
        
        c1, c2, c3, c4 = st.columns(4)

        # --- 1. Gender Analysis ---
        with c1:
            st.info("**Gender Analysis**")
            gender_freq = {
                'Male': results['gender_analysis']['male_count'],
                'Female': results['gender_analysis']['female_count']
            }
            filtered_gender_freq = {k: v for k, v in gender_freq.items() if v > 0}
            
            fig_gender = create_donut_chart(filtered_gender_freq, "Gender Breakdown")
            if fig_gender:
                st.plotly_chart(fig_gender, use_container_width=True)
            else:
                st.write("No gendered words found.")
            
            render_sentiment_context(results['gender_analysis']['sentiment_scores'])
            
            with st.expander("Show Details"):
                st.markdown("**Male:**")
                st.json(results['gender_analysis']['male_words_freq'])
                st.markdown("**Female:**")
                st.json(results['gender_analysis']['female_words_freq'])

        # --- 2. Religion Analysis ---
        with c2:
            st.info("**Religion Analysis**")
            religion_freq = results['religion_analysis']['words_freq']
            fig_religion = create_donut_chart(religion_freq, "Religion Terms Breakdown")
            
            if fig_religion:
                st.plotly_chart(fig_religion, use_container_width=True)
            else:
                st.write("No religious terms found.")
            
            render_sentiment_context(results['religion_analysis']['sentiment_scores'])

            with st.expander("Show Details"):
                st.json(religion_freq)

        # --- 3. Nationality/Ethnicity Analysis ---
        with c3:
            st.info("**Nationality/Ethnicity Analysis**")
            nat_eth_freq = results['nationality_ethnicity_analysis']['words_freq']
            #Merging "Middle" + "Eastern" in One Chart Section
            filtered_nat_freq = {k: v for k, v in nat_eth_freq.items() if k not in ['middle', 'eastern']}
            if 'middle' in nat_eth_freq or 'eastern' in nat_eth_freq:
                me_count = nat_eth_freq.get('middle', nat_eth_freq.get('eastern', 0))
                filtered_nat_freq['Middle Eastern'] = me_count
            
            fig_nat_eth = create_donut_chart(filtered_nat_freq, "Nationality/Ethnicity Breakdown")
            
            if fig_nat_eth:
                st.plotly_chart(fig_nat_eth, use_container_width=True)
            else:
                st.write("No nationality/ethnicity terms found.")
            
            render_sentiment_context(results['nationality_ethnicity_analysis']['sentiment_scores'])
            
            with st.expander("Show Details"):
                st.json(nat_eth_freq)
        
        # --- 4. Occupational Analysis ---
        with c4:
            st.info("**Occupational Analysis**")
            occupation_freq = {
                'Male-Coded Jobs': results['occupation_analysis']['male_job_count'],
                'Female-Coded Jobs': results['occupation_analysis']['female_job_count']
            }
            filtered_occupation_freq = {k: v for k, v in occupation_freq.items() if v > 0}
            
            fig_occupation = create_donut_chart(filtered_occupation_freq, "Occupational Breakdown")
            
            if fig_occupation:
                st.plotly_chart(fig_occupation, use_container_width=True)
            else:
                st.write("No occupational terms found.")
            
            render_sentiment_context(results['occupation_analysis']['sentiment_scores'])
            
            with st.expander("Show Details"):
                st.markdown("**Male-Coded:**")
                st.json(results['occupation_analysis']['male_job_freq'])
                st.markdown("**Female-Coded:**")
                st.json(results['occupation_analysis']['female_job_freq'])
            
    else:
        st.warning("Please enter some text to analyze first.")

# --- About Section ---
st.markdown("---")
st.header("About this Project")
st.write("""
This dashboard was created as a university project for the "Selected Topic (Fourth Industrial Revolution and 100 Years of AI, 1950–2025)" course. 
The goal is to demonstrate how NLP can be used to identify potential social biases in text.
""")
st.markdown("---")
st.subheader("Done By: Reema Alhazmi")
st.markdown("[My 𝕏 (a.k.a Twitter) Profile](https://twitter.com/1cllo0)")
st.markdown("[My LinkedIn Profile](https://www.linkedin.com/in/reema-alhazmi-62328724a)")

